// <auto-generated />
using System;
using Helpdesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helpdesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260922001342_InicialSuporte")]
    partial class InicialSuporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Domain.Suporte.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("texto");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_comentarios");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_comentarios_ticket_id");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Domain.Suporte.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset?>("PausadoDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pausado_desde");

                    b.Property<DateTimeOffset>("PrazoPrimeiraResposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_primeira_resposta");

                    b.Property<DateTimeOffset>("PrazoResolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_resolucao");

                    b.Property<DateTimeOffset?>("PrimeiraRespostaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeira_resposta_em");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<DateTimeOffset?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_tickets_tenant_id_status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Domain.Suporte.Comentario", b =>
                {
                    b.HasOne("Helpdesk.Domain.Suporte.Ticket", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_tickets_ticket_id");
                });

            modelBuilder.Entity("Helpdesk.Domain.Suporte.Ticket", b =>
                {
                    b.OwnsOne("Helpdesk.Domain.Suporte.PrazosSla", "Sla", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("PrimeiraResposta")
                                .HasColumnType("interval")
                                .HasColumnName("sla_primeira_resposta");

                            b1.Property<TimeSpan>("Resolucao")
                                .HasColumnType("interval")
                                .HasColumnName("sla_resolucao");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId")
                                .HasConstraintName("fk_tickets_tickets_id");
                        });

                    b.Navigation("Sla")
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Domain.Suporte.Ticket", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
