/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TicketResumoDto"][];
                        "application/json": components["schemas"]["TicketResumoDto"][];
                        "text/json": components["schemas"]["TicketResumoDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AbrirTicketRequest"];
                    "text/json": components["schemas"]["AbrirTicketRequest"];
                    "application/*+json": components["schemas"]["AbrirTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/assumir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TicketDetalheDto"];
                        "application/json": components["schemas"]["TicketDetalheDto"];
                        "text/json": components["schemas"]["TicketDetalheDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ComentarTicketRequest"];
                    "text/json": components["schemas"]["ComentarTicketRequest"];
                    "application/*+json": components["schemas"]["ComentarTicketRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AbrirTicketRequest: {
            titulo: string;
            descricao: string;
            prioridade: components["schemas"]["Prioridade"];
        };
        ComentarTicketRequest: {
            texto: string;
        };
        ComentarioDto: {
            /** Format: uuid */
            autorId: string;
            texto: string;
            /** Format: date-time */
            criadoEm: string;
        };
        LoginRequest: {
            /** Format: uuid */
            tenantId: string;
            email: string;
            senha: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expiraEm: string;
        };
        /** @enum {string} */
        Prioridade: "Baixa" | "Media" | "Alta" | "Critica";
        /** @enum {string} */
        StatusTicket: "Aberto" | "EmAtendimento" | "AguardandoCliente" | "Resolvido" | "Fechado" | "Reaberto";
        TicketDetalheDto: {
            /** Format: uuid */
            id: string;
            titulo: string;
            descricao: string;
            prioridade: components["schemas"]["Prioridade"];
            status: components["schemas"]["StatusTicket"];
            /** Format: uuid */
            solicitanteId: string;
            /** Format: uuid */
            responsavelId?: string | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            prazoPrimeiraResposta: string;
            /** Format: date-time */
            prazoResolucao: string;
            comentarios: components["schemas"]["ComentarioDto"][];
        };
        TicketResumoDto: {
            /** Format: uuid */
            id: string;
            titulo: string;
            prioridade: components["schemas"]["Prioridade"];
            status: components["schemas"]["StatusTicket"];
            /** Format: uuid */
            solicitanteId: string;
            /** Format: uuid */
            responsavelId?: string | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            prazoPrimeiraResposta: string;
            /** Format: date-time */
            prazoResolucao: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
